flowchart TB
  subgraph Internet
    USER[User Browser]
  end

  subgraph Edge["GCP Edge"]
    DNS[Cloud DNS]
    IP[Static Global IP]
    ARMOR[Cloud Armor]
    ING[GCE Ingress + TLS]
  end

  subgraph VPC["boutique-vpc"]
    subgraph GKE["Private GKE"]
      subgraph NS_B["namespace: boutique"]
        FE[frontend]
        SVC[Microservices]
        REDIS[(Redis)]
      end
      subgraph NS_A["namespace: argocd"]
        AC[Argo CD]
      end
      subgraph NS_M["namespace: monitoring"]
        OTEL[OTel Collector]
      end
    end
    NAT[Cloud NAT]
  end

  USER --> DNS --> IP --> ARMOR --> ING --> FE
  FE --> SVC --> REDIS
  SVC --> NAT
  OTEL --> NAT
